### ISSUE TITLE
GISAID Upload Pipeline

### ISSUE THREAD

**Issue by chacalle** [blab/nextstrain-db#10]
When incorporating new sequences from GISAID into nextflu, are only relatively new sequences downloaded or is everything in GISAID downloaded? `vdb_parse` currently parses the fasta before trying to upload each sequence and checking if the virus is already in vdb. If all sequences from GISAID are going to be in the fasta each time, it will take a while to determine the lineage for all sequences. In this case `vdb_parse` should immediately check for the virus in vdb after getting the strain name. If only relatively new GISAID sequences are in the fasta then this isn't a problem.

**Comment by trvrb** [comment]
This has been resolved by `vdb/flu_update.py -db vdb -v flu --update_groupings`.
