### ISSUE TITLE
Automatic Uploading of Sequences from Genbank

### ISSUE THREAD

**Issue by chacalle** [blab/nextstrain-db#14]
Create function to regularly search through entrez for new sequences to upload. I think this would be useful if there are multiple nextstrain websites being maintained, could automate retrieving new sequences from genbank.

Can query with entrez like `"Zika virus"[porgn] AND ("2015/01/01"[MDAT] : "2016-04-14"[MDAT]) AND ("10000"[SLEN] : "100000000"[SLEN])`. Possibly also only include sequences that include `complete genome` in their description. Using entrez seems to lag slightly behind manually searching genbank (missing new sequences KX051563, KX056898 at the moment). 

Will want some sort of staging area that shows important sequence information where someone could approve sequences for uploading. Possibly email new sequence information and accession numbers to user for approval?

**Comment by trvrb** [comment]
This is a great direction. I'm going to shelve for the moment. Now that the data is basically working, we could start to think about smarter upload scripts. This should integrate well with the overall nextstrain pipeline.

**Comment by chacalle** [comment]
If the VIPR had an API we could automate the search and download we're doing for ZIKA and other viruses in the future.

**Comment by trvrb** [comment]
Yes. This would be awesome.
