### ISSUE TITLE
Citation not updating

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#25]
The previous `RuntimeError: Search Backend failed: Database is not supported: nuccore` error has resolved itself on NCBI's end. I was update to add citations to most strains via `python vdb/update.py -db vdb -v zika`. However, some aren't taking. Trying for example:

```
python vdb/update.py -db vdb -v zika --accessions KX087102
```

The Genbank [entry](http://www.ncbi.nlm.nih.gov/nuccore/KX087102) is lacking a `title`, but does have authors. The running `update` is not revising `authors` however.

There are a number of other accessions that behave the same way. Checkout `new_server.vdb.zika` and look for strains that have `null` for `authors`.

**Comment by chacalle** [comment]
Update wasn't finding the correct strain name, it now uses zika_upload.fix_name() to parse the correct strain name. I believe zika_update now works.

**Comment by trvrb** [comment]
This is working as intended now. Thanks!
