### ISSUE TITLE
Should separate concepts of 'table' and 'virus' in vdb

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#26]
For the ZIBRA project, it will be easiest to have a separate table within vdb. I'm setting this up now as `vdb/zibra`. However, this should still have a `virus` field that says `zika`. We can be merging `vdb/zibra` into `vdb/zika` based on shared fields.

I'd suggest changing `-v zibra` / `-v flu` to `-t zibra` / `-t flu`. So swapping "virus" for "table". You could have a command that looks like:

```
python vdb/zibra_upload.py -db vdb -t zibra --fname seq.fasta --source zibra --virus zika
```

that uploads sequences to the `vdb/zibra` table, but still labels each `virus` field as `zika`.

I suspect this will be a generally useful semantic separation as well.

**Comment by chacalle** [comment]
Made branch `table_field`. Added `-tb --table` argument, `-v --virus` is still an argument. Basically changed all the lines that were using the rethink module, now they talk to `self.table` instead of `self.virus`.

**Comment by trvrb** [comment]
Great! I merged this into `master`. Consider it resolved.
