### ISSUE TITLE
More flexible field requirements

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#27]
@chacalle ---

I'm realizing now that we should be more flexible with field requirements. It had been set up to reject documents that lack a few key attributes like `date`, `country`, etc... I think this is overly restrictive. I think it would be better if a document is still added to the database but has `date` = `null`, `county` = `null`, etc... The only "required" field when uploading should be `strain`.

I would move these "required" fields to downloading instead. By default, we could only download viruses with defined `date`, `country`, etc...

I changed the required fields here:

https://github.com/blab/nextstrain-db/blob/master/vdb/upload.py#L54

I think I fixed everything here, but could you test a bit?

**Comment by chacalle** [comment]
Tested this and it seems to work well! We could make the default "required" fields what you need for nextstrain-augur, since that's the main use.

**Comment by trvrb** [comment]
Okay. Thanks. Let's go with the current required fields for the moment.
