### ISSUE TITLE
Improve field updates

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#28]
@chacalle ---

The current ZiBRA pipeline is to add documents to the database without sequence information via a tsv file:

https://github.com/blab/nextstrain-db/blob/master/ZIBRA.md#database-commands

And then to add matched FASTAs that just contain:

```
>strainA
ATCGCTG...
>strainB
ATCGCTG...
```

I hacked together this functionality here:

https://github.com/blab/nextstrain-db/blob/master/vdb/upload.py#L305

but it's not very clean. It should be possible to have a document with any complement of fields with defined values and fields marked `null` and then to 'upload' a document with the same primary key (`strain`) that has some overlap in terms of fields and non-null values. The merged document should replace all `null` values with the new defined value, but only overwrite non-null if the `--overwrite` option is passed.

For example,

db document:
* `date`: `2016-XX-XX`
* `country`: `brazil`
* `sequences`:
 * `accession`: `null`
 * `locus`: `null`
 * `sequence`: `null`

upload document:
* `date`: `2016-01-01`
* `country`: `null`
* `sequences`:
 * `accession`: `160123456789`
 * `locus`: `genome`
 * `sequence`: `ATGCTGCCTGC`

With default upload, the resulting db document should be:
* `date`: `2016-XX-XX`
* `country`: `brazil`
* `sequences`:
 * `accession`: `160123456789`
 * `locus`: `genome`
 * `sequence`: `ATGCTGCCTGC`

With `--overwrite` upload, the resulting db document should be:
* `date`: `2016-01-01`
* `country`: `brazil`
* `sequences`:
 * `accession`: `160123456789`
 * `locus`: `genome`
 * `sequence`: `ATGCTGCCTGC`

**Comment by chacalle** [comment]
If the codes working how I think it is, I think this would work if we just the overwritable fields (https://github.com/blab/nextstrain-db/blob/master/vdb/upload.py#L58) as I see you've done. Is it still not working as you like when you do that?

**Comment by chacalle** [comment]
Also is the schema setup where we can store multiple sequences for each strain proving useful and needed?

**Comment by trvrb** [comment]
I was having a problem with updating `sequences` field until I added df20f9461b608f236413659511c2b520e58a95d4. Before it was appending rather than updating, so in the above example it would have resulted in:
* `date`: `2016-XX-XX`
* `country`: `brazil`
* `sequences`:
 * 1
  * `accession`: `null`
  * `locus`: `null`
  * `sequence`: `null`
 * 2
  * `accession`: `160123456789`
  * `locus`: `genome`
  * `sequence`: `ATGCTGCCTGC`

The logic to the current code seems to work, but is really not that clean.

>Also is the schema setup where we can store multiple sequences for each strain proving useful and needed?

I think this isn't so helpful for Zika, but it should be completely necessary for flu (for multiple segments and vaccine strains that are sequenced again and again). I don't see a way around it.

**Comment by chacalle** [comment]
The `sequences` and `citations` is the hard part and isn't really clean as a result. The reason you ran into this problem is that the current code looks for a matching `accession` if it's not `null`, otherwise it looks for a matching sequence (like when downloading sequences from virological w/o accessions). I hadn't considered uploading documents w/o sequence information, but I'm not sure if there is a much cleaner way of doing this with our current schema.

**Comment by chacalle** [comment]
We could possibly have two versions of vdb. One with the current schema and code that allows for multiple sequences to be stored for each strain (for this version have to find the corresponding accession/sequence to overwrite values) and a second version that is a simpler flat schema that only allows one sequence per strain (can easily overwrite any null values in the document).

**Comment by trvrb** [comment]
I like this idea. I would make vdb know about which schema is being used by looking for the magic `sequences` field vs the magic `sequence` field. If the former is found then we treat the database as now. If the latter, we treat it as a flatter structure.

**Comment by trvrb** [comment]
It would be really nice if running `vdb/download.py` would work on tables formatted with either schema.

**Comment by chacalle** [comment]
This `schema` branch now just passes through `format_schema` so everything is flat. It just updates every field using https://github.com/blab/nextstrain-db/blob/schema/vdb/upload.py#L284. `download` and `zika_update` work with this too.

**Comment by trvrb** [comment]
@chacalle ---

Thanks for push here! A couple things on the `schema` branch:

1. Take a look at what I did here: 86082ebc7dcb60d016885ecad94bcbc5da7a684e + 81682d0f8f5e895d7e2d38a39ceabbc4aa06f85e. We want to be able to update any of the fields. But still being careful never to overwrite a non-null value. And when `--overwrite` is called, we still don't replace a non-null value with a null value in the input file.

2. It feels wrong to have such a heavy `format_schema` in `zika_upload`.

**Comment by chacalle** [comment]
I merged in the changes you made along with the ones I made earlier. Good point with 2. I included [`self.simple_schema`](https://github.com/blab/nextstrain-db/blob/schema/vdb/zika_upload.py#L11) in `zika_upload` to fix that.

**Comment by chacalle** [comment]
I ran `python vdb/zika_upload.py -db test_vdb -tb zika --fname zika_vipr.fasta --source genbank --locus genome --v zika`, then `python vdb/zika_update.py -db test_vdb -tb zika`, then `python vdb/download.py -db test_vdb -tb zika` to test it.

**Comment by trvrb** [comment]
Thanks! I'll do some testing now.

**Comment by trvrb** [comment]
The new schema fixes this.
