### ISSUE TITLE
Dates not downloading properly

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#37]
I just tried to run `python vdb/download.py -db vdb -v zika --fstem zika` and I got:

```
>Zhejiang04|zika|KX117076|?|china|china|china|china|genbank|genome|Zhang et al
>1_0015_PF|zika|KX447511|?|oceania|french_polynesia|french_polynesia|french_polynesia|vipr|genome|Nougairede et al
```

All the `collection_dates` have been replaced with `?`. Not exactly sure what's going on here. All the dates in the db itself look fine. Strangely `python vdb/download.py -db vdb -v zika --fstem zika --ftype json` is working just as it should.

**Comment by chacalle** [comment]
I think we've been using `zika_download.py` which is why we haven't seen this bug. So `python vdb/zika_download.py -db vdb -v zika --fstem zika`. Changed the default fasta fields in `download.py` to align with `zika_download.py` though.

**Comment by trvrb** [comment]
User error 😬. Sorry about that. Thanks for amending.

**Comment by chacalle** [comment]
No problem. It might make sense to switch to just one download script that gets called and then the virus argument determines what methods need to be overwritten/added. This would reduce the confusion of specifying both `zika_download` and `-v zika`.
